name = "startup-guide"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/worker"

[env.production]
vars = { NODE_ENV = "production" }

[env.production.vars]
# Environment variables will be set via Cloudflare dashboard
